[project]
name = "ansr-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.2",
    "firebase-admin>=7.1.0",
    "pydantic>=2.12.0",
    "uvicorn>=0.37.0",
]
